// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sphere.proto

package proto_sphere

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StratumShareState int32

const (
	StratumShareState_SUC_SOLVE_SHARE          StratumShareState = 0
	StratumShareState_SUC_SUBMIT_BLOCK         StratumShareState = 1
	StratumShareState_ERR_DUPLICATE_SHARE      StratumShareState = 2
	StratumShareState_ERR_LOW_DIFFICULTY_SHARE StratumShareState = 3
	StratumShareState_ERR_JOB_NOT_FOUND        StratumShareState = 4
	StratumShareState_ERR_SUBMIT_BLOCK         StratumShareState = 5
)

var StratumShareState_name = map[int32]string{
	0: "SUC_SOLVE_SHARE",
	1: "SUC_SUBMIT_BLOCK",
	2: "ERR_DUPLICATE_SHARE",
	3: "ERR_LOW_DIFFICULTY_SHARE",
	4: "ERR_JOB_NOT_FOUND",
	5: "ERR_SUBMIT_BLOCK",
}
var StratumShareState_value = map[string]int32{
	"SUC_SOLVE_SHARE":          0,
	"SUC_SUBMIT_BLOCK":         1,
	"ERR_DUPLICATE_SHARE":      2,
	"ERR_LOW_DIFFICULTY_SHARE": 3,
	"ERR_JOB_NOT_FOUND":        4,
	"ERR_SUBMIT_BLOCK":         5,
}

func (x StratumShareState) String() string {
	return proto.EnumName(StratumShareState_name, int32(x))
}
func (StratumShareState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{0}
}

type StratumJob struct {
	PrevHash             string          `protobuf:"bytes,1,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	CoinBase1            string          `protobuf:"bytes,2,opt,name=coin_base1,json=coinBase1,proto3" json:"coin_base1,omitempty"`
	CoinBase2            string          `protobuf:"bytes,3,opt,name=coin_base2,json=coinBase2,proto3" json:"coin_base2,omitempty"`
	MerkleBranch         []string        `protobuf:"bytes,4,rep,name=merkle_branch,json=merkleBranch,proto3" json:"merkle_branch,omitempty"`
	Version              string          `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	NBits                string          `protobuf:"bytes,6,opt,name=n_bits,json=nBits,proto3" json:"n_bits,omitempty"`
	Meta                 *StratumJobMeta `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StratumJob) Reset()         { *m = StratumJob{} }
func (m *StratumJob) String() string { return proto.CompactTextString(m) }
func (*StratumJob) ProtoMessage()    {}
func (*StratumJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{0}
}
func (m *StratumJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StratumJob.Unmarshal(m, b)
}
func (m *StratumJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StratumJob.Marshal(b, m, deterministic)
}
func (dst *StratumJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StratumJob.Merge(dst, src)
}
func (m *StratumJob) XXX_Size() int {
	return xxx_messageInfo_StratumJob.Size(m)
}
func (m *StratumJob) XXX_DiscardUnknown() {
	xxx_messageInfo_StratumJob.DiscardUnknown(m)
}

var xxx_messageInfo_StratumJob proto.InternalMessageInfo

func (m *StratumJob) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (m *StratumJob) GetCoinBase1() string {
	if m != nil {
		return m.CoinBase1
	}
	return ""
}

func (m *StratumJob) GetCoinBase2() string {
	if m != nil {
		return m.CoinBase2
	}
	return ""
}

func (m *StratumJob) GetMerkleBranch() []string {
	if m != nil {
		return m.MerkleBranch
	}
	return nil
}

func (m *StratumJob) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StratumJob) GetNBits() string {
	if m != nil {
		return m.NBits
	}
	return ""
}

func (m *StratumJob) GetMeta() *StratumJobMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type StratumJobMeta struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	MinTimeTs            int32    `protobuf:"varint,2,opt,name=minTimeTs,proto3" json:"minTimeTs,omitempty"`
	CurTimeTs            int32    `protobuf:"varint,3,opt,name=curTimeTs,proto3" json:"curTimeTs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StratumJobMeta) Reset()         { *m = StratumJobMeta{} }
func (m *StratumJobMeta) String() string { return proto.CompactTextString(m) }
func (*StratumJobMeta) ProtoMessage()    {}
func (*StratumJobMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{1}
}
func (m *StratumJobMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StratumJobMeta.Unmarshal(m, b)
}
func (m *StratumJobMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StratumJobMeta.Marshal(b, m, deterministic)
}
func (dst *StratumJobMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StratumJobMeta.Merge(dst, src)
}
func (m *StratumJobMeta) XXX_Size() int {
	return xxx_messageInfo_StratumJobMeta.Size(m)
}
func (m *StratumJobMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_StratumJobMeta.DiscardUnknown(m)
}

var xxx_messageInfo_StratumJobMeta proto.InternalMessageInfo

func (m *StratumJobMeta) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *StratumJobMeta) GetMinTimeTs() int32 {
	if m != nil {
		return m.MinTimeTs
	}
	return 0
}

func (m *StratumJobMeta) GetCurTimeTs() int32 {
	if m != nil {
		return m.CurTimeTs
	}
	return 0
}

type SysInfo struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysInfo) Reset()         { *m = SysInfo{} }
func (m *SysInfo) String() string { return proto.CompactTextString(m) }
func (*SysInfo) ProtoMessage()    {}
func (*SysInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{2}
}
func (m *SysInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysInfo.Unmarshal(m, b)
}
func (m *SysInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysInfo.Marshal(b, m, deterministic)
}
func (dst *SysInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysInfo.Merge(dst, src)
}
func (m *SysInfo) XXX_Size() int {
	return xxx_messageInfo_SysInfo.Size(m)
}
func (m *SysInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SysInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SysInfo proto.InternalMessageInfo

func (m *SysInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *SysInfo) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type StratumConfig struct {
	PoolTag              string   `protobuf:"bytes,1,opt,name=pool_tag,json=poolTag,proto3" json:"pool_tag,omitempty"`
	PayoutAddress        string   `protobuf:"bytes,2,opt,name=payout_address,json=payoutAddress,proto3" json:"payout_address,omitempty"`
	CoinType             string   `protobuf:"bytes,3,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	UsedTestNet          bool     `protobuf:"varint,4,opt,name=used_test_net,json=usedTestNet,proto3" json:"used_test_net,omitempty"`
	ExtraNonce1Length    int32    `protobuf:"varint,5,opt,name=extra_nonce1_length,json=extraNonce1Length,proto3" json:"extra_nonce1_length,omitempty"`
	ExtraNonce2Length    int32    `protobuf:"varint,6,opt,name=extra_nonce2_length,json=extraNonce2Length,proto3" json:"extra_nonce2_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StratumConfig) Reset()         { *m = StratumConfig{} }
func (m *StratumConfig) String() string { return proto.CompactTextString(m) }
func (*StratumConfig) ProtoMessage()    {}
func (*StratumConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{3}
}
func (m *StratumConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StratumConfig.Unmarshal(m, b)
}
func (m *StratumConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StratumConfig.Marshal(b, m, deterministic)
}
func (dst *StratumConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StratumConfig.Merge(dst, src)
}
func (m *StratumConfig) XXX_Size() int {
	return xxx_messageInfo_StratumConfig.Size(m)
}
func (m *StratumConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StratumConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StratumConfig proto.InternalMessageInfo

func (m *StratumConfig) GetPoolTag() string {
	if m != nil {
		return m.PoolTag
	}
	return ""
}

func (m *StratumConfig) GetPayoutAddress() string {
	if m != nil {
		return m.PayoutAddress
	}
	return ""
}

func (m *StratumConfig) GetCoinType() string {
	if m != nil {
		return m.CoinType
	}
	return ""
}

func (m *StratumConfig) GetUsedTestNet() bool {
	if m != nil {
		return m.UsedTestNet
	}
	return false
}

func (m *StratumConfig) GetExtraNonce1Length() int32 {
	if m != nil {
		return m.ExtraNonce1Length
	}
	return 0
}

func (m *StratumConfig) GetExtraNonce2Length() int32 {
	if m != nil {
		return m.ExtraNonce2Length
	}
	return 0
}

type RegisterRequest struct {
	Config               *StratumConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	SysInfo              *SysInfo       `protobuf:"bytes,2,opt,name=sys_info,json=sysInfo,proto3" json:"sys_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{4}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetConfig() *StratumConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *RegisterRequest) GetSysInfo() *SysInfo {
	if m != nil {
		return m.SysInfo
	}
	return nil
}

type RegisterResponse struct {
	RegisterId           string   `protobuf:"bytes,1,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{5}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

type GetLatestStratumJobRequest struct {
	RegisterId           string   `protobuf:"bytes,1,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestStratumJobRequest) Reset()         { *m = GetLatestStratumJobRequest{} }
func (m *GetLatestStratumJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestStratumJobRequest) ProtoMessage()    {}
func (*GetLatestStratumJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{6}
}
func (m *GetLatestStratumJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestStratumJobRequest.Unmarshal(m, b)
}
func (m *GetLatestStratumJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestStratumJobRequest.Marshal(b, m, deterministic)
}
func (dst *GetLatestStratumJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestStratumJobRequest.Merge(dst, src)
}
func (m *GetLatestStratumJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestStratumJobRequest.Size(m)
}
func (m *GetLatestStratumJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestStratumJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestStratumJobRequest proto.InternalMessageInfo

func (m *GetLatestStratumJobRequest) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

type GetLatestStratumJobResponse struct {
	Job                  *StratumJob `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetLatestStratumJobResponse) Reset()         { *m = GetLatestStratumJobResponse{} }
func (m *GetLatestStratumJobResponse) String() string { return proto.CompactTextString(m) }
func (*GetLatestStratumJobResponse) ProtoMessage()    {}
func (*GetLatestStratumJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{7}
}
func (m *GetLatestStratumJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestStratumJobResponse.Unmarshal(m, b)
}
func (m *GetLatestStratumJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestStratumJobResponse.Marshal(b, m, deterministic)
}
func (dst *GetLatestStratumJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestStratumJobResponse.Merge(dst, src)
}
func (m *GetLatestStratumJobResponse) XXX_Size() int {
	return xxx_messageInfo_GetLatestStratumJobResponse.Size(m)
}
func (m *GetLatestStratumJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestStratumJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestStratumJobResponse proto.InternalMessageInfo

func (m *GetLatestStratumJobResponse) GetJob() *StratumJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type StratumShare struct {
	Version              string            `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ExtraNonce1          string            `protobuf:"bytes,2,opt,name=extra_nonce1,json=extraNonce1,proto3" json:"extra_nonce1,omitempty"`
	ExtraNonce2          string            `protobuf:"bytes,3,opt,name=extra_nonce2,json=extraNonce2,proto3" json:"extra_nonce2,omitempty"`
	NTime                string            `protobuf:"bytes,4,opt,name=n_time,json=nTime,proto3" json:"n_time,omitempty"`
	NBits                string            `protobuf:"bytes,5,opt,name=n_bits,json=nBits,proto3" json:"n_bits,omitempty"`
	Nonce                string            `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PrevHash             string            `protobuf:"bytes,7,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	CoinBase1            string            `protobuf:"bytes,8,opt,name=coin_base1,json=coinBase1,proto3" json:"coin_base1,omitempty"`
	CoinBase2            string            `protobuf:"bytes,9,opt,name=coin_base2,json=coinBase2,proto3" json:"coin_base2,omitempty"`
	Meta                 *StratumShareMeta `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StratumShare) Reset()         { *m = StratumShare{} }
func (m *StratumShare) String() string { return proto.CompactTextString(m) }
func (*StratumShare) ProtoMessage()    {}
func (*StratumShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{8}
}
func (m *StratumShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StratumShare.Unmarshal(m, b)
}
func (m *StratumShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StratumShare.Marshal(b, m, deterministic)
}
func (dst *StratumShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StratumShare.Merge(dst, src)
}
func (m *StratumShare) XXX_Size() int {
	return xxx_messageInfo_StratumShare.Size(m)
}
func (m *StratumShare) XXX_DiscardUnknown() {
	xxx_messageInfo_StratumShare.DiscardUnknown(m)
}

var xxx_messageInfo_StratumShare proto.InternalMessageInfo

func (m *StratumShare) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StratumShare) GetExtraNonce1() string {
	if m != nil {
		return m.ExtraNonce1
	}
	return ""
}

func (m *StratumShare) GetExtraNonce2() string {
	if m != nil {
		return m.ExtraNonce2
	}
	return ""
}

func (m *StratumShare) GetNTime() string {
	if m != nil {
		return m.NTime
	}
	return ""
}

func (m *StratumShare) GetNBits() string {
	if m != nil {
		return m.NBits
	}
	return ""
}

func (m *StratumShare) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *StratumShare) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (m *StratumShare) GetCoinBase1() string {
	if m != nil {
		return m.CoinBase1
	}
	return ""
}

func (m *StratumShare) GetCoinBase2() string {
	if m != nil {
		return m.CoinBase2
	}
	return ""
}

func (m *StratumShare) GetMeta() *StratumShareMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type StratumShareMeta struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	CurTimeTs            int32    `protobuf:"varint,2,opt,name=curTimeTs,proto3" json:"curTimeTs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StratumShareMeta) Reset()         { *m = StratumShareMeta{} }
func (m *StratumShareMeta) String() string { return proto.CompactTextString(m) }
func (*StratumShareMeta) ProtoMessage()    {}
func (*StratumShareMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{9}
}
func (m *StratumShareMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StratumShareMeta.Unmarshal(m, b)
}
func (m *StratumShareMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StratumShareMeta.Marshal(b, m, deterministic)
}
func (dst *StratumShareMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StratumShareMeta.Merge(dst, src)
}
func (m *StratumShareMeta) XXX_Size() int {
	return xxx_messageInfo_StratumShareMeta.Size(m)
}
func (m *StratumShareMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_StratumShareMeta.DiscardUnknown(m)
}

var xxx_messageInfo_StratumShareMeta proto.InternalMessageInfo

func (m *StratumShareMeta) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *StratumShareMeta) GetCurTimeTs() int32 {
	if m != nil {
		return m.CurTimeTs
	}
	return 0
}

type SubmitShareRequest struct {
	RegisterId           string        `protobuf:"bytes,1,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	Share                *StratumShare `protobuf:"bytes,2,opt,name=share,proto3" json:"share,omitempty"`
	Difficulty           uint64        `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SubmitShareRequest) Reset()         { *m = SubmitShareRequest{} }
func (m *SubmitShareRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitShareRequest) ProtoMessage()    {}
func (*SubmitShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{10}
}
func (m *SubmitShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitShareRequest.Unmarshal(m, b)
}
func (m *SubmitShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitShareRequest.Marshal(b, m, deterministic)
}
func (dst *SubmitShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitShareRequest.Merge(dst, src)
}
func (m *SubmitShareRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitShareRequest.Size(m)
}
func (m *SubmitShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitShareRequest proto.InternalMessageInfo

func (m *SubmitShareRequest) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

func (m *SubmitShareRequest) GetShare() *StratumShare {
	if m != nil {
		return m.Share
	}
	return nil
}

func (m *SubmitShareRequest) GetDifficulty() uint64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

type SubmitShareResponse struct {
	Result               *SubmitShareResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubmitShareResponse) Reset()         { *m = SubmitShareResponse{} }
func (m *SubmitShareResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitShareResponse) ProtoMessage()    {}
func (*SubmitShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{11}
}
func (m *SubmitShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitShareResponse.Unmarshal(m, b)
}
func (m *SubmitShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitShareResponse.Marshal(b, m, deterministic)
}
func (dst *SubmitShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitShareResponse.Merge(dst, src)
}
func (m *SubmitShareResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitShareResponse.Size(m)
}
func (m *SubmitShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitShareResponse proto.InternalMessageInfo

func (m *SubmitShareResponse) GetResult() *SubmitShareResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type SubmitShareResult struct {
	State                StratumShareState `protobuf:"varint,1,opt,name=state,proto3,enum=proto_sphere.StratumShareState" json:"state,omitempty"`
	ComputePower         float64           `protobuf:"fixed64,2,opt,name=compute_power,json=computePower,proto3" json:"compute_power,omitempty"`
	Hash                 string            `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SubmitShareResult) Reset()         { *m = SubmitShareResult{} }
func (m *SubmitShareResult) String() string { return proto.CompactTextString(m) }
func (*SubmitShareResult) ProtoMessage()    {}
func (*SubmitShareResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{12}
}
func (m *SubmitShareResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitShareResult.Unmarshal(m, b)
}
func (m *SubmitShareResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitShareResult.Marshal(b, m, deterministic)
}
func (dst *SubmitShareResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitShareResult.Merge(dst, src)
}
func (m *SubmitShareResult) XXX_Size() int {
	return xxx_messageInfo_SubmitShareResult.Size(m)
}
func (m *SubmitShareResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitShareResult.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitShareResult proto.InternalMessageInfo

func (m *SubmitShareResult) GetState() StratumShareState {
	if m != nil {
		return m.State
	}
	return StratumShareState_SUC_SOLVE_SHARE
}

func (m *SubmitShareResult) GetComputePower() float64 {
	if m != nil {
		return m.ComputePower
	}
	return 0
}

func (m *SubmitShareResult) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ClearShareHistoryRequest struct {
	RegisterId           string   `protobuf:"bytes,1,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearShareHistoryRequest) Reset()         { *m = ClearShareHistoryRequest{} }
func (m *ClearShareHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*ClearShareHistoryRequest) ProtoMessage()    {}
func (*ClearShareHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{13}
}
func (m *ClearShareHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearShareHistoryRequest.Unmarshal(m, b)
}
func (m *ClearShareHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearShareHistoryRequest.Marshal(b, m, deterministic)
}
func (dst *ClearShareHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearShareHistoryRequest.Merge(dst, src)
}
func (m *ClearShareHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_ClearShareHistoryRequest.Size(m)
}
func (m *ClearShareHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearShareHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearShareHistoryRequest proto.InternalMessageInfo

func (m *ClearShareHistoryRequest) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

func (m *ClearShareHistoryRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ClearShareHistoryResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearShareHistoryResponse) Reset()         { *m = ClearShareHistoryResponse{} }
func (m *ClearShareHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*ClearShareHistoryResponse) ProtoMessage()    {}
func (*ClearShareHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{14}
}
func (m *ClearShareHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearShareHistoryResponse.Unmarshal(m, b)
}
func (m *ClearShareHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearShareHistoryResponse.Marshal(b, m, deterministic)
}
func (dst *ClearShareHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearShareHistoryResponse.Merge(dst, src)
}
func (m *ClearShareHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_ClearShareHistoryResponse.Size(m)
}
func (m *ClearShareHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearShareHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearShareHistoryResponse proto.InternalMessageInfo

func (m *ClearShareHistoryResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type UnRegisterRequest struct {
	RegisterId           string   `protobuf:"bytes,1,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnRegisterRequest) Reset()         { *m = UnRegisterRequest{} }
func (m *UnRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UnRegisterRequest) ProtoMessage()    {}
func (*UnRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{15}
}
func (m *UnRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterRequest.Unmarshal(m, b)
}
func (m *UnRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterRequest.Marshal(b, m, deterministic)
}
func (dst *UnRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterRequest.Merge(dst, src)
}
func (m *UnRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UnRegisterRequest.Size(m)
}
func (m *UnRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterRequest proto.InternalMessageInfo

func (m *UnRegisterRequest) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

type UnRegisterResponse struct {
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnRegisterResponse) Reset()         { *m = UnRegisterResponse{} }
func (m *UnRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UnRegisterResponse) ProtoMessage()    {}
func (*UnRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sphere_de0c0e0c62b77ac1, []int{16}
}
func (m *UnRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterResponse.Unmarshal(m, b)
}
func (m *UnRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterResponse.Marshal(b, m, deterministic)
}
func (dst *UnRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterResponse.Merge(dst, src)
}
func (m *UnRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UnRegisterResponse.Size(m)
}
func (m *UnRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterResponse proto.InternalMessageInfo

func (m *UnRegisterResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*StratumJob)(nil), "proto_sphere.StratumJob")
	proto.RegisterType((*StratumJobMeta)(nil), "proto_sphere.StratumJobMeta")
	proto.RegisterType((*SysInfo)(nil), "proto_sphere.SysInfo")
	proto.RegisterType((*StratumConfig)(nil), "proto_sphere.StratumConfig")
	proto.RegisterType((*RegisterRequest)(nil), "proto_sphere.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "proto_sphere.RegisterResponse")
	proto.RegisterType((*GetLatestStratumJobRequest)(nil), "proto_sphere.GetLatestStratumJobRequest")
	proto.RegisterType((*GetLatestStratumJobResponse)(nil), "proto_sphere.GetLatestStratumJobResponse")
	proto.RegisterType((*StratumShare)(nil), "proto_sphere.StratumShare")
	proto.RegisterType((*StratumShareMeta)(nil), "proto_sphere.StratumShareMeta")
	proto.RegisterType((*SubmitShareRequest)(nil), "proto_sphere.SubmitShareRequest")
	proto.RegisterType((*SubmitShareResponse)(nil), "proto_sphere.SubmitShareResponse")
	proto.RegisterType((*SubmitShareResult)(nil), "proto_sphere.SubmitShareResult")
	proto.RegisterType((*ClearShareHistoryRequest)(nil), "proto_sphere.ClearShareHistoryRequest")
	proto.RegisterType((*ClearShareHistoryResponse)(nil), "proto_sphere.ClearShareHistoryResponse")
	proto.RegisterType((*UnRegisterRequest)(nil), "proto_sphere.UnRegisterRequest")
	proto.RegisterType((*UnRegisterResponse)(nil), "proto_sphere.UnRegisterResponse")
	proto.RegisterEnum("proto_sphere.StratumShareState", StratumShareState_name, StratumShareState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SphereClient is the client API for Sphere service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SphereClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetLatestStratumJob(ctx context.Context, in *GetLatestStratumJobRequest, opts ...grpc.CallOption) (*GetLatestStratumJobResponse, error)
	Subscribe(ctx context.Context, in *GetLatestStratumJobRequest, opts ...grpc.CallOption) (Sphere_SubscribeClient, error)
	SubmitShare(ctx context.Context, in *SubmitShareRequest, opts ...grpc.CallOption) (*SubmitShareResponse, error)
	ClearShareHistory(ctx context.Context, in *ClearShareHistoryRequest, opts ...grpc.CallOption) (*ClearShareHistoryResponse, error)
	UnRegister(ctx context.Context, in *UnRegisterRequest, opts ...grpc.CallOption) (*UnRegisterResponse, error)
}

type sphereClient struct {
	cc *grpc.ClientConn
}

func NewSphereClient(cc *grpc.ClientConn) SphereClient {
	return &sphereClient{cc}
}

func (c *sphereClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/proto_sphere.Sphere/register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) GetLatestStratumJob(ctx context.Context, in *GetLatestStratumJobRequest, opts ...grpc.CallOption) (*GetLatestStratumJobResponse, error) {
	out := new(GetLatestStratumJobResponse)
	err := c.cc.Invoke(ctx, "/proto_sphere.Sphere/getLatestStratumJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) Subscribe(ctx context.Context, in *GetLatestStratumJobRequest, opts ...grpc.CallOption) (Sphere_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sphere_serviceDesc.Streams[0], "/proto_sphere.Sphere/subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &sphereSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Sphere_SubscribeClient interface {
	Recv() (*GetLatestStratumJobResponse, error)
	grpc.ClientStream
}

type sphereSubscribeClient struct {
	grpc.ClientStream
}

func (x *sphereSubscribeClient) Recv() (*GetLatestStratumJobResponse, error) {
	m := new(GetLatestStratumJobResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sphereClient) SubmitShare(ctx context.Context, in *SubmitShareRequest, opts ...grpc.CallOption) (*SubmitShareResponse, error) {
	out := new(SubmitShareResponse)
	err := c.cc.Invoke(ctx, "/proto_sphere.Sphere/submitShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) ClearShareHistory(ctx context.Context, in *ClearShareHistoryRequest, opts ...grpc.CallOption) (*ClearShareHistoryResponse, error) {
	out := new(ClearShareHistoryResponse)
	err := c.cc.Invoke(ctx, "/proto_sphere.Sphere/clearShareHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) UnRegister(ctx context.Context, in *UnRegisterRequest, opts ...grpc.CallOption) (*UnRegisterResponse, error) {
	out := new(UnRegisterResponse)
	err := c.cc.Invoke(ctx, "/proto_sphere.Sphere/unRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SphereServer is the server API for Sphere service.
type SphereServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetLatestStratumJob(context.Context, *GetLatestStratumJobRequest) (*GetLatestStratumJobResponse, error)
	Subscribe(*GetLatestStratumJobRequest, Sphere_SubscribeServer) error
	SubmitShare(context.Context, *SubmitShareRequest) (*SubmitShareResponse, error)
	ClearShareHistory(context.Context, *ClearShareHistoryRequest) (*ClearShareHistoryResponse, error)
	UnRegister(context.Context, *UnRegisterRequest) (*UnRegisterResponse, error)
}

func RegisterSphereServer(s *grpc.Server, srv SphereServer) {
	s.RegisterService(&_Sphere_serviceDesc, srv)
}

func _Sphere_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_sphere.Sphere/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_GetLatestStratumJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestStratumJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).GetLatestStratumJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_sphere.Sphere/GetLatestStratumJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).GetLatestStratumJob(ctx, req.(*GetLatestStratumJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLatestStratumJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SphereServer).Subscribe(m, &sphereSubscribeServer{stream})
}

type Sphere_SubscribeServer interface {
	Send(*GetLatestStratumJobResponse) error
	grpc.ServerStream
}

type sphereSubscribeServer struct {
	grpc.ServerStream
}

func (x *sphereSubscribeServer) Send(m *GetLatestStratumJobResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Sphere_SubmitShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).SubmitShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_sphere.Sphere/SubmitShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).SubmitShare(ctx, req.(*SubmitShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_ClearShareHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearShareHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).ClearShareHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_sphere.Sphere/ClearShareHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).ClearShareHistory(ctx, req.(*ClearShareHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_UnRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).UnRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_sphere.Sphere/UnRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).UnRegister(ctx, req.(*UnRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sphere_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_sphere.Sphere",
	HandlerType: (*SphereServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register",
			Handler:    _Sphere_Register_Handler,
		},
		{
			MethodName: "getLatestStratumJob",
			Handler:    _Sphere_GetLatestStratumJob_Handler,
		},
		{
			MethodName: "submitShare",
			Handler:    _Sphere_SubmitShare_Handler,
		},
		{
			MethodName: "clearShareHistory",
			Handler:    _Sphere_ClearShareHistory_Handler,
		},
		{
			MethodName: "unRegister",
			Handler:    _Sphere_UnRegister_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "subscribe",
			Handler:       _Sphere_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sphere.proto",
}

func init() { proto.RegisterFile("sphere.proto", fileDescriptor_sphere_de0c0e0c62b77ac1) }

var fileDescriptor_sphere_de0c0e0c62b77ac1 = []byte{
	// 1049 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x72, 0xda, 0x46,
	0x14, 0x8e, 0xf8, 0xe7, 0x80, 0x13, 0xbc, 0x8e, 0x53, 0x05, 0x3b, 0x0e, 0x51, 0xa7, 0xad, 0x9b,
	0xe9, 0x78, 0x1c, 0xdc, 0x4e, 0xae, 0x7a, 0x61, 0xb0, 0x5d, 0x93, 0x10, 0x93, 0x2e, 0xd0, 0x4e,
	0xaf, 0x76, 0x04, 0x2c, 0x48, 0x2d, 0x48, 0xaa, 0x76, 0x95, 0x86, 0xeb, 0x5e, 0xf4, 0x3d, 0xfa,
	0x18, 0xbd, 0xeb, 0x13, 0x75, 0xa6, 0x4f, 0xd0, 0xd9, 0xd5, 0x0a, 0x24, 0xd9, 0xd8, 0xbe, 0xe9,
	0x15, 0xda, 0xef, 0x7c, 0x7b, 0xce, 0x9e, 0x9f, 0xef, 0x00, 0x55, 0xe6, 0x59, 0xd4, 0xa7, 0x47,
	0x9e, 0xef, 0x72, 0x17, 0x55, 0xe5, 0x0f, 0x09, 0x31, 0xe3, 0x1f, 0x0d, 0xa0, 0xcf, 0x7d, 0x93,
	0x07, 0x8b, 0x37, 0xee, 0x08, 0xed, 0x41, 0xd9, 0xf3, 0xe9, 0x07, 0x62, 0x99, 0xcc, 0xd2, 0xb5,
	0x86, 0x76, 0x58, 0xc6, 0x25, 0x01, 0x5c, 0x9a, 0xcc, 0x42, 0xcf, 0x00, 0xc6, 0xae, 0xed, 0x90,
	0x91, 0xc9, 0xe8, 0x2b, 0x3d, 0x23, 0xad, 0x65, 0x81, 0xb4, 0x04, 0x90, 0x30, 0x37, 0xf5, 0x6c,
	0xd2, 0xdc, 0x44, 0x9f, 0xc2, 0xd6, 0x82, 0xfa, 0xbf, 0xcc, 0x29, 0x19, 0xf9, 0xa6, 0x33, 0xb6,
	0xf4, 0x5c, 0x23, 0x7b, 0x58, 0xc6, 0xd5, 0x10, 0x6c, 0x49, 0x0c, 0xe9, 0x50, 0xfc, 0x40, 0x7d,
	0x66, 0xbb, 0x8e, 0x9e, 0x97, 0x0e, 0xa2, 0x23, 0xda, 0x85, 0x82, 0x43, 0x46, 0x36, 0x67, 0x7a,
	0x41, 0x1a, 0xf2, 0x4e, 0xcb, 0xe6, 0x0c, 0x1d, 0x43, 0x6e, 0x41, 0xb9, 0xa9, 0x17, 0x1b, 0xda,
	0x61, 0xa5, 0xb9, 0x7f, 0x14, 0x4f, 0xee, 0x68, 0x9d, 0xd8, 0x3b, 0xca, 0x4d, 0x2c, 0x99, 0xc6,
	0x04, 0x1e, 0x26, 0x71, 0xf4, 0x04, 0x0a, 0x16, 0xb5, 0x67, 0x16, 0x97, 0x19, 0xe7, 0xb1, 0x3a,
	0xa1, 0x7d, 0x28, 0x2f, 0x6c, 0x67, 0x60, 0x2f, 0xe8, 0x80, 0xc9, 0x74, 0xf3, 0x78, 0x0d, 0x08,
	0xeb, 0x38, 0xf0, 0x95, 0x35, 0x1b, 0x5a, 0x57, 0x80, 0xf1, 0x1a, 0x8a, 0xfd, 0x25, 0xeb, 0x38,
	0x53, 0x17, 0xd5, 0xa1, 0x64, 0xb9, 0x8c, 0x3b, 0xe6, 0x82, 0x46, 0x25, 0x8d, 0xce, 0xa8, 0x06,
	0x59, 0xcf, 0x9e, 0x28, 0xe7, 0xe2, 0xd3, 0xf8, 0x57, 0x83, 0x2d, 0xf5, 0xbe, 0xb6, 0xeb, 0x4c,
	0xed, 0x19, 0x7a, 0x0a, 0x25, 0xcf, 0x75, 0xe7, 0x84, 0x9b, 0x33, 0x75, 0xbf, 0x28, 0xce, 0x03,
	0x73, 0x86, 0x3e, 0x83, 0x87, 0x9e, 0xb9, 0x74, 0x03, 0x4e, 0xcc, 0xc9, 0xc4, 0xa7, 0x8c, 0xa9,
	0xae, 0x6c, 0x85, 0xe8, 0x69, 0x08, 0x8a, 0xae, 0xca, 0xce, 0xf0, 0xa5, 0x47, 0x55, 0x63, 0x4a,
	0x02, 0x18, 0x2c, 0x3d, 0x8a, 0x0c, 0xd8, 0x0a, 0x18, 0x9d, 0x10, 0x4e, 0x19, 0x27, 0x0e, 0xe5,
	0x7a, 0xae, 0xa1, 0x1d, 0x96, 0x70, 0x45, 0x80, 0x03, 0xca, 0xf8, 0x15, 0xe5, 0xe8, 0x08, 0x76,
	0xe8, 0x47, 0xee, 0x9b, 0xc4, 0x71, 0x9d, 0x31, 0x7d, 0x45, 0xe6, 0xd4, 0x99, 0x71, 0x4b, 0xb6,
	0x28, 0x8f, 0xb7, 0xa5, 0xe9, 0x4a, 0x5a, 0xba, 0xd2, 0x90, 0xe2, 0x37, 0x23, 0x7e, 0x21, 0xcd,
	0x6f, 0x86, 0x7c, 0xe3, 0x23, 0x3c, 0xc2, 0x74, 0x66, 0x33, 0x4e, 0x7d, 0x4c, 0x7f, 0x0d, 0x28,
	0xe3, 0xe8, 0x04, 0x0a, 0x63, 0x99, 0xbf, 0xcc, 0xb9, 0xd2, 0xdc, 0xbb, 0xb1, 0xb5, 0x61, 0x89,
	0xb0, 0xa2, 0xa2, 0x63, 0x28, 0xb1, 0x25, 0x23, 0xb6, 0x33, 0x75, 0x65, 0x25, 0x2a, 0xcd, 0xdd,
	0xd4, 0xb5, 0xb0, 0x27, 0xb8, 0xc8, 0xc2, 0x0f, 0xe3, 0x04, 0x6a, 0xeb, 0xc8, 0xcc, 0x73, 0x1d,
	0x46, 0xd1, 0x73, 0xa8, 0xf8, 0x0a, 0x23, 0xf6, 0x44, 0xd5, 0x1c, 0x22, 0xa8, 0x33, 0x31, 0xbe,
	0x85, 0xfa, 0x77, 0x94, 0x77, 0x4d, 0x51, 0xb2, 0xf5, 0x2c, 0x45, 0x2f, 0xbf, 0xf3, 0x7a, 0x07,
	0xf6, 0x6e, 0xbc, 0xae, 0xc2, 0xbf, 0x84, 0xec, 0xcf, 0xee, 0x48, 0xa5, 0xad, 0x6f, 0x9a, 0x68,
	0x2c, 0x48, 0xc6, 0xdf, 0x19, 0xa8, 0x2a, 0xac, 0x6f, 0x99, 0x3e, 0x8d, 0x0b, 0x48, 0x4b, 0x0a,
	0xe8, 0x05, 0x54, 0xe3, 0x3d, 0x54, 0x93, 0x52, 0x89, 0x35, 0x2f, 0x45, 0x89, 0x34, 0x1c, 0xa3,
	0x34, 0x43, 0x19, 0x72, 0x7b, 0x41, 0xe5, 0x98, 0x08, 0x19, 0x8a, 0x81, 0x8f, 0xa9, 0x33, 0x1f,
	0x57, 0xe7, 0x63, 0xc8, 0x4b, 0x57, 0x2b, 0xcd, 0x8a, 0x43, 0x72, 0xc9, 0x14, 0x6f, 0x5d, 0x32,
	0xa5, 0xdb, 0x97, 0x4c, 0x39, 0xbd, 0x64, 0x9a, 0x6a, 0x1d, 0x80, 0x2c, 0xde, 0xc1, 0x8d, 0xc5,
	0x93, 0x85, 0x8a, 0x2d, 0x84, 0x4b, 0xa8, 0xa5, 0x2d, 0xb7, 0xad, 0x84, 0xb5, 0xe8, 0x33, 0x69,
	0xd1, 0xff, 0xa1, 0x01, 0xea, 0x07, 0xa3, 0x85, 0xcd, 0xa5, 0xa7, 0xfb, 0x0e, 0x04, 0x3a, 0x86,
	0x3c, 0x13, 0x17, 0xd4, 0xcc, 0xd6, 0x37, 0x3f, 0x1b, 0x87, 0x44, 0x74, 0x00, 0x30, 0xb1, 0xa7,
	0x53, 0x7b, 0x1c, 0xcc, 0xf9, 0x52, 0xf6, 0x29, 0x87, 0x63, 0x88, 0x71, 0x05, 0x3b, 0x89, 0x87,
	0xa8, 0xd1, 0x7a, 0x0d, 0x05, 0x9f, 0xb2, 0x60, 0xce, 0xd5, 0x74, 0x3d, 0x4f, 0x45, 0x4a, 0x5c,
	0x09, 0xe6, 0x1c, 0x2b, 0xba, 0xf1, 0xbb, 0x06, 0xdb, 0xd7, 0xac, 0xe8, 0x1b, 0xc8, 0x33, 0x6e,
	0xf2, 0x70, 0xad, 0x3d, 0xbc, 0xe6, 0x2d, 0xf6, 0xee, 0xbe, 0xa0, 0xe1, 0x90, 0x2d, 0xfe, 0x09,
	0xc6, 0xee, 0xc2, 0x0b, 0x38, 0x25, 0x9e, 0xfb, 0x1b, 0xf5, 0x65, 0xda, 0x1a, 0xae, 0x2a, 0xf0,
	0xbd, 0xc0, 0x10, 0x82, 0x9c, 0x9c, 0x8f, 0x70, 0x06, 0xe5, 0xb7, 0xd1, 0x07, 0xbd, 0x3d, 0xa7,
	0xa6, 0x2f, 0x5d, 0x5e, 0xda, 0x8c, 0xbb, 0xfe, 0xf2, 0xde, 0x45, 0x5e, 0xb7, 0x34, 0x13, 0x6f,
	0xa9, 0x71, 0x02, 0x4f, 0x6f, 0x70, 0xaa, 0x0a, 0xf6, 0x24, 0x51, 0xb0, 0xd2, 0xaa, 0x1e, 0x5f,
	0xc3, 0xf6, 0xd0, 0x49, 0xaf, 0xac, 0x3b, 0x85, 0xff, 0x15, 0xa0, 0xf8, 0xad, 0x6b, 0x31, 0x32,
	0xf1, 0x18, 0x2f, 0xff, 0x14, 0x35, 0x4f, 0xd7, 0x10, 0xed, 0xc0, 0xa3, 0xfe, 0xb0, 0x4d, 0xfa,
	0xbd, 0xee, 0x0f, 0xe7, 0xa4, 0x7f, 0x79, 0x8a, 0xcf, 0x6b, 0x0f, 0xd0, 0x63, 0xa8, 0x49, 0x70,
	0xd8, 0x7a, 0xd7, 0x19, 0x90, 0x56, 0xb7, 0xd7, 0x7e, 0x5b, 0xd3, 0xd0, 0x27, 0xb0, 0x73, 0x8e,
	0x31, 0x39, 0x1b, 0xbe, 0xef, 0x76, 0xda, 0xa7, 0x83, 0x88, 0x9e, 0x41, 0xfb, 0xa0, 0x0b, 0x43,
	0xb7, 0xf7, 0x23, 0x39, 0xeb, 0x5c, 0x5c, 0x74, 0xda, 0xc3, 0xee, 0xe0, 0x27, 0x65, 0xcd, 0xa2,
	0x5d, 0xd8, 0x16, 0xd6, 0x37, 0xbd, 0x16, 0xb9, 0xea, 0x0d, 0xc8, 0x45, 0x6f, 0x78, 0x75, 0x56,
	0xcb, 0x89, 0x18, 0x02, 0x4e, 0xc4, 0xc8, 0x37, 0xff, 0xca, 0x41, 0xa1, 0x2f, 0xfb, 0x8d, 0xde,
	0x42, 0x29, 0xca, 0x15, 0x3d, 0x4b, 0x8e, 0x42, 0xaa, 0x52, 0xf5, 0x83, 0x4d, 0xe6, 0xb0, 0x24,
	0xc6, 0x03, 0x34, 0x87, 0x9d, 0xd9, 0xf5, 0x1d, 0x89, 0x0e, 0x93, 0x17, 0x37, 0x6f, 0xe1, 0xfa,
	0x97, 0xf7, 0x60, 0xae, 0xa2, 0x4d, 0xa0, 0xcc, 0x82, 0x11, 0x1b, 0xfb, 0xf6, 0x88, 0xfe, 0x4f,
	0x31, 0x8e, 0x35, 0x34, 0x80, 0x0a, 0x5b, 0x6b, 0x08, 0x35, 0x6e, 0x11, 0x5f, 0xe8, 0xff, 0xc5,
	0x6d, 0xf2, 0x8c, 0xde, 0x3e, 0x85, 0xed, 0x71, 0x7a, 0x7e, 0xd1, 0xe7, 0xc9, 0x9b, 0x9b, 0x54,
	0x53, 0xff, 0xe2, 0x4e, 0xde, 0x2a, 0xce, 0xf7, 0x00, 0xc1, 0x6a, 0x78, 0x51, 0x4a, 0xeb, 0xd7,
	0xc4, 0x50, 0x6f, 0x6c, 0x26, 0x44, 0x2e, 0x47, 0x05, 0x49, 0x39, 0xf9, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x0d, 0xfc, 0x6c, 0x61, 0xa1, 0x0a, 0x00, 0x00,
}
